export const AUTH_START = 'AUTH START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_REDIRECT_PATCH = 'AUTH_REDIRECT_PATCH';

export const EDIT_EXERCISES_INIT = 'EDIT_EXERCISES_INIT';
export const EDIT_EXERCISES_UPDATE = 'EDIT_EXERCISES_UPDATE';
export const EDIT_EXERCISES_UP = 'EDIT_EXERCISES_UP';
export const EDIT_EXERCISES_DOWN = 'EDIT_EXERCISES_DOWN';
export const EDIT_EXERCISES_DELETE = 'EDIT_EXERCISES_DELETE';
export const EDIT_EXERCISES_START = 'EDIT_EXERCISES_START';
export const EDIT_EXERCISES_SUCCESS = 'EDIT_EXERCISES_SUCCESS';
export const EDIT_EXERCISES_FAIL = 'EDIT_EXERCISES_FAIL';

export const NEW_EXERCISES_INIT = 'NEW_EXERCISES_INIT';
export const NEW_EXERCISES_UPDATE = 'NEW_EXERCISES_UPDATE';
export const NEW_EXERCISES_START = 'NEW_EXERCISES_START';
export const NEW_EXERCISES_SUCCESS = 'NEW_EXERCISES_SUCCESS';
export const NEW_EXERCISES_FAIL = 'NEW_EXERCISES_FAIL';

export const VERIFICATION_NEW_USER_INIT = 'VERIFICATION_NEW_USER_INIT';
export const VERIFICATION_NEW_USER_START = 'VERIFICATION_NEW_USER_START';
export const VERIFICATION_NEW_USER_SUCCESS = 'VERIFICATION_NEW_USER_SUCCESS';
export const VERIFICATION_NEW_USER_FAIL = 'VERIFICATION_NEW_USER_FAIL';

export const WORKOUT_INIT = 'WORKOUT_INIT';
export const WORKOUT_START = 'WORKOUT_START';
export const WORKOUT_SUCCESS = 'WORKOUT_SUCCESS';
export const WORKOUT_FAIL = 'WORKOUT_FAIL';

export const EDIT_WORKOUT_ADD = 'EDIT_WORKOUT_ADD'
export const EDIT_WORKOUT_DELETE = 'EDIT_WORKOUT_DELETE'
export const EDIT_WORKOUT_UPDATE = 'EDIT_WORKOUT_UPDATE'
export const EDIT_WORKOUT_UP = 'EDIT_WORKOUT_UP'
export const EDIT_WORKOUT_DOWN = 'EDIT_WORKOUT_DOWN'
